name: build

on:
  push:
    branches:
      - master
  pull_request:
    types: [ opened, synchronize ]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ windows-latest, macOS-latest, ubuntu-latest ]

    steps:
    - uses: actions/checkout@v1

    - name: .NET Build
      run: dotnet build --configuration Release

    - name: .NET Test
      run: dotnet test --configuration Release --no-build