name: deploy

on:
  check_suite:
    types: completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master' && github.event.check_suite.conclusion == 'success'
    
    steps:
      - uses: actions/checkout@v1
      - name: .NET Pack
        run: dotnet pack --configuration Release
      - name: Push(NuGet)
        run: dotnet nuget push **/*.nupkg --api-key $TOKEN
        env:
          TOKEN: ${{ secrets.NUGET_API_KEY }}
      - name: Push(GitHub Package Registry)
        run: |
          nuget sources add -name "GPR" -Source $SOURCE -Username $GITHUB_ACTOR -Password $TOKEN
          nuget push **/*.nupkg -Source "GPR" 
        env:
          SOURCE: https://nuget.pkg.github.com/$GITHUB_ACTOR/index.json
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
