name: .NET Core

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ windows-latest, macOS-latest, ubuntu-latest ]
        dotnet: [ 3.0.100 ]

    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ matrix.dotnet }}
    - name: .NET Build
      run: dotnet build --configuration Release
    - name: .NET Test
      run: dotnet test --configuration Release
