name: release

on:
  push:
    branches:
      - master

jobs:
  release-note:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Release Drafter
      uses: toolmantim/release-drafter@v5.2.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}